-- auction-starter-tables.sql -- SQL table definitions
-- Auction Web Application Project
--
-- C S 105: PHP/SQL, Spring 2016, J. Thywissen
-- The University of Texas at Austin
--

-- - - - - - - - -
-- Create tables
-- - - - - - - - -

CREATE TABLE PERSON (
    PERSON_ID INTEGER PRIMARY KEY,
    SURNAME VARCHAR(96) NOT NULL,
    FORENAME VARCHAR(96),
    PASSWORD VARCHAR(96),
    EMAIL_ADDRESS VARCHAR(255) NOT NULL );

CREATE TABLE AUCTION_STATUS (
    AUCTION_STATUS_ID INTEGER PRIMARY KEY,
    NAME VARCHAR(20) NOT NULL );

CREATE TABLE ITEM_CATEGORY (
    ITEM_CATEGORY_ID INTEGER PRIMARY KEY,
    NAME VARCHAR(78) NOT NULL );

CREATE TABLE AUCTION (
    AUCTION_ID INTEGER PRIMARY KEY,
    STATUS INTEGER NOT NULL,
    SELLER INTEGER NOT NULL,
    OPEN_TIME TIMESTAMP,
    CLOSE_TIME TIMESTAMP,
    CURRENT_PRICE INTEGER,
    ITEM_CATEGORY INTEGER,
    ITEM_CAPTION VARCHAR(78),
    ITEM_DESCRIPTION VARCHAR(998),
    ITEM_PHOTO MEDIUMBLOB,
    WINNER_ID INTEGER NOT NULL);

CREATE INDEX AUCTION_STATUS_INDEX ON AUCTION (STATUS);

CREATE INDEX AUCTION_SELLER_INDEX ON AUCTION (SELLER);

CREATE INDEX AUCTION_ITEM_CATEGORY_INDEX ON AUCTION (ITEM_CATEGORY);

ALTER TABLE AUCTION ADD FOREIGN KEY (STATUS) REFERENCES AUCTION_STATUS(AUCTION_STATUS_ID);

ALTER TABLE AUCTION ADD FOREIGN KEY (SELLER) REFERENCES PERSON(PERSON_ID);

ALTER TABLE AUCTION ADD FOREIGN KEY (ITEM_CATEGORY) REFERENCES ITEM_CATEGORY(ITEM_CATEGORY_ID);


-- - - - - - - - -
-- Insert sample data
-- - - - - - - - -

INSERT INTO PERSON VALUES (1, 'Vo', 'Jayson','abc123','jaysonvo97@gmail.com');
INSERT INTO PERSON VALUES (2, 'Murthy', 'Akhil','abc123', 'akhilm@example.com');
INSERT INTO PERSON VALUES (3, 'Milligan', 'Dillan','abc123', 'dillianm@example.com');

INSERT INTO AUCTION_STATUS VALUES (1, 'Open');
INSERT INTO AUCTION_STATUS VALUES (2, 'Closed');
INSERT INTO AUCTION_STATUS VALUES (3, 'Won');
INSERT INTO AUCTION_STATUS VALUES (4, 'Paid');

INSERT INTO ITEM_CATEGORY VALUES (1, 'Antiques');
INSERT INTO ITEM_CATEGORY VALUES (2, 'Art & Collectibles');
INSERT INTO ITEM_CATEGORY VALUES (3, 'Books & Movies & Music');
INSERT INTO ITEM_CATEGORY VALUES (4, 'Cars');
INSERT INTO ITEM_CATEGORY VALUES (5, 'Clothing');
INSERT INTO ITEM_CATEGORY VALUES (6, 'Computers & Electronics');
INSERT INTO ITEM_CATEGORY VALUES (7, 'Jewelry');
INSERT INTO ITEM_CATEGORY VALUES (8, 'Musical Instruments');
INSERT INTO ITEM_CATEGORY VALUES (9, 'Tools');
INSERT INTO ITEM_CATEGORY VALUES (10, 'Toys');

INSERT INTO AUCTION VALUES (1, 1, 1, '2016-02-12 15:37:00', '2016-02-16  23:00:00',55, 1, 'Coffee Test', 'Antique coffee mug from Texas', NULL,1);
INSERT INTO AUCTION VALUES (2, 1, 2, '2016-02-13 17:05:00', '2016-02-16  23:00:00',555, 6, 'Toshiba Laptop Intel Core i5 with 16GB RAM ', 'Intel Core i5 with 16GB RAM  Intel Core i5 with 16GB RAM  Intel Core i5 with 16GB RAM  Intel Core i5 with 16GB RAM ', NULL,2);
INSERT INTO AUCTION VALUES (3, 1, 3, '2016-02-14 17:06:00', '2016-02-16  23:00:00',5, 5, 'Abercrombie jeans', 'Lightly used jeans by a high school freshman.', NULL,3);
